export interface Recomendation {
  id: number;
  name: string;
  img: string;
  type: string;
}

export const recomendations: Recomendation[] = [
  {
    id: 52991,
    name: "Sousou no Frieren",
    img: "https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",
    type: "anime",
  },
  {
    id: 5114,
    name: "Fullmetal Alchemist: Brotherhood",
    img: "https://cdn.myanimelist.net/images/anime/1208/94745l.jpg",
    type: "anime",
  },
  {
    id: 9253,
    name: "Steins;Gate",
    img: "https://cdn.myanimelist.net/images/anime/1935/127974l.jpg",
    type: "anime",
  },
  {
    id: 28977,
    name: "Gintama°",
    img: "https://cdn.myanimelist.net/images/anime/3/72078l.jpg",
    type: "anime",
  },
  {
    id: 38524,
    name: "Shingeki no Kyojin Season 3 Part 2",
    img: "https://cdn.myanimelist.net/images/anime/1517/100633l.jpg",
    type: "anime",
  },
  {
    id: 39486,
    name: "Gintama: The Final",
    img: "https://cdn.myanimelist.net/images/anime/1245/116760l.jpg",
    type: "anime",
  },
  {
    id: 11061,
    name: "Hunter x Hunter (2011)",
    img: "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
    type: "anime",
  },
  {
    id: 9969,
    name: "Gintama'",
    img: "https://cdn.myanimelist.net/images/anime/4/50361l.jpg",
    type: "anime",
  },
  {
    id: 41467,
    name: "Bleach: Sennen Kessen-hen",
    img: "https://cdn.myanimelist.net/images/anime/1908/135431l.jpg",
    type: "anime",
  },
  {
    id: 15417,
    name: "Gintama': Enchousen",
    img: "https://cdn.myanimelist.net/images/anime/1452/123686l.jpg",
    type: "anime",
  },
  {
    id: 820,
    name: "Ginga Eiyuu Densetsu",
    img: "https://cdn.myanimelist.net/images/anime/13/13225l.jpg",
    type: "anime",
  },
  {
    id: 43608,
    name: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    img: "https://cdn.myanimelist.net/images/anime/1160/122627l.jpg",
    type: "anime",
  },
  {
    id: 34096,
    name: "Gintama.",
    img: "https://cdn.myanimelist.net/images/anime/3/83528l.jpg",
    type: "anime",
  },
  {
    id: 42938,
    name: "Fruits Basket: The Final",
    img: "https://cdn.myanimelist.net/images/anime/1085/114792l.jpg",
    type: "anime",
  },
  {
    id: 918,
    name: "Gintama",
    img: "https://cdn.myanimelist.net/images/anime/10/73274l.jpg",
    type: "anime",
  },
  {
    id: 51535,
    name: "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    img: "https://cdn.myanimelist.net/images/anime/1279/131078l.jpg",
    type: "anime",
  },
  {
    id: 4181,
    name: "Clannad: After Story",
    img: "https://cdn.myanimelist.net/images/anime/1299/110774l.jpg",
    type: "anime",
  },
  {
    id: 28851,
    name: "Koe no Katachi",
    img: "https://cdn.myanimelist.net/images/anime/1122/96435l.jpg",
    type: "anime",
  },
  {
    id: 35180,
    name: "3-gatsu no Lion 2nd Season",
    img: "https://cdn.myanimelist.net/images/anime/3/88469l.jpg",
    type: "anime",
  },
  {
    id: 15335,
    name: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
    img: "https://cdn.myanimelist.net/images/anime/10/51723l.jpg",
    type: "anime",
  },
  {
    id: 2904,
    name: "Code Geass: Hangyaku no Lelouch R2",
    img: "https://cdn.myanimelist.net/images/anime/1088/135089l.jpg",
    type: "anime",
  },
  {
    id: 37491,
    name: "Gintama.: Shirogane no Tamashii-hen - Kouhan-sen",
    img: "https://cdn.myanimelist.net/images/anime/1776/96566l.jpg",
    type: "anime",
  },
  {
    id: 37987,
    name: "Violet Evergarden Movie",
    img: "https://cdn.myanimelist.net/images/anime/1825/110716l.jpg",
    type: "anime",
  },
  {
    id: 51009,
    name: "Jujutsu Kaisen 2nd Season",
    img: "https://cdn.myanimelist.net/images/anime/1792/138022l.jpg",
    type: "anime",
  },
  {
    id: 19,
    name: "Monster",
    img: "https://cdn.myanimelist.net/images/anime/10/18793l.jpg",
    type: "anime",
  },

  {
    id: 52991,
    name: "Sousou no Frieren",
    img: "https://cdn.myanimelist.net/images/anime/1015/138006l.jpg",
    type: "anime",
  },
  {
    id: 5114,
    name: "Fullmetal Alchemist: Brotherhood",
    img: "https://cdn.myanimelist.net/images/anime/1208/94745l.jpg",
    type: "anime",
  },
  {
    id: 9253,
    name: "Steins;Gate",
    img: "https://cdn.myanimelist.net/images/anime/1935/127974l.jpg",
    type: "anime",
  },
  {
    id: 28977,
    name: "Gintama°",
    img: "https://cdn.myanimelist.net/images/anime/3/72078l.jpg",
    type: "anime",
  },
  {
    id: 38524,
    name: "Shingeki no Kyojin Season 3 Part 2",
    img: "https://cdn.myanimelist.net/images/anime/1517/100633l.jpg",
    type: "anime",
  },
  {
    id: 39486,
    name: "Gintama: The Final",
    img: "https://cdn.myanimelist.net/images/anime/1245/116760l.jpg",
    type: "anime",
  },
  {
    id: 11061,
    name: "Hunter x Hunter (2011)",
    img: "https://cdn.myanimelist.net/images/anime/1337/99013l.jpg",
    type: "anime",
  },
  {
    id: 9969,
    name: "Gintama'",
    img: "https://cdn.myanimelist.net/images/anime/4/50361l.jpg",
    type: "anime",
  },
  {
    id: 41467,
    name: "Bleach: Sennen Kessen-hen",
    img: "https://cdn.myanimelist.net/images/anime/1908/135431l.jpg",
    type: "anime",
  },
  {
    id: 15417,
    name: "Gintama': Enchousen",
    img: "https://cdn.myanimelist.net/images/anime/1452/123686l.jpg",
    type: "anime",
  },
  {
    id: 820,
    name: "Ginga Eiyuu Densetsu",
    img: "https://cdn.myanimelist.net/images/anime/13/13225l.jpg",
    type: "anime",
  },
  {
    id: 43608,
    name: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    img: "https://cdn.myanimelist.net/images/anime/1160/122627l.jpg",
    type: "anime",
  },
  {
    id: 34096,
    name: "Gintama.",
    img: "https://cdn.myanimelist.net/images/anime/3/83528l.jpg",
    type: "anime",
  },
  {
    id: 42938,
    name: "Fruits Basket: The Final",
    img: "https://cdn.myanimelist.net/images/anime/1085/114792l.jpg",
    type: "anime",
  },
  {
    id: 918,
    name: "Gintama",
    img: "https://cdn.myanimelist.net/images/anime/10/73274l.jpg",
    type: "anime",
  },
  {
    id: 51535,
    name: "Shingeki no Kyojin: The Final Season - Kanketsu-hen",
    img: "https://cdn.myanimelist.net/images/anime/1279/131078l.jpg",
    type: "anime",
  },
  {
    id: 4181,
    name: "Clannad: After Story",
    img: "https://cdn.myanimelist.net/images/anime/1299/110774l.jpg",
    type: "anime",
  },
  {
    id: 28851,
    name: "Koe no Katachi",
    img: "https://cdn.myanimelist.net/images/anime/1122/96435l.jpg",
    type: "anime",
  },
  {
    id: 35180,
    name: "3-gatsu no Lion 2nd Season",
    img: "https://cdn.myanimelist.net/images/anime/3/88469l.jpg",
    type: "anime",
  },
  {
    id: 15335,
    name: "Gintama Movie 2: Kanketsu-hen - Yorozuya yo Eien Nare",
    img: "https://cdn.myanimelist.net/images/anime/10/51723l.jpg",
    type: "anime",
  },
  {
    id: 2904,
    name: "Code Geass: Hangyaku no Lelouch R2",
    img: "https://cdn.myanimelist.net/images/anime/1088/135089l.jpg",
    type: "anime",
  },
  {
    id: 37491,
    name: "Gintama.: Shirogane no Tamashii-hen - Kouhan-sen",
    img: "https://cdn.myanimelist.net/images/anime/1776/96566l.jpg",
    type: "anime",
  },
  {
    id: 37987,
    name: "Violet Evergarden Movie",
    img: "https://cdn.myanimelist.net/images/anime/1825/110716l.jpg",
    type: "anime",
  },
  {
    id: 51009,
    name: "Jujutsu Kaisen 2nd Season",
    img: "https://cdn.myanimelist.net/images/anime/1792/138022l.jpg",
    type: "anime",
  },
  {
    id: 19,
    name: "Monster",
    img: "https://cdn.myanimelist.net/images/anime/10/18793l.jpg",
    type: "anime",
  },

  {
    id: 2,
    name: "Berserk",
    img: "https://cdn.myanimelist.net/images/manga/1/157897l.jpg",
    type: "manga",
  },
  {
    id: 1706,
    name: "JoJo no Kimyou na Bouken Part 7: Steel Ball Run",
    img: "https://cdn.myanimelist.net/images/manga/3/179882l.jpg",
    type: "manga",
  },
  {
    id: 656,
    name: "Vagabond",
    img: "https://cdn.myanimelist.net/images/manga/1/259070l.jpg",
    type: "manga",
  },
  {
    id: 13,
    name: "One Piece",
    img: "https://cdn.myanimelist.net/images/manga/2/253146l.jpg",
    type: "manga",
  },
  {
    id: 1,
    name: "Monster",
    img: "https://cdn.myanimelist.net/images/manga/3/258224l.jpg",
    type: "manga",
  },
  {
    id: 51,
    name: "Slam Dunk",
    img: "https://cdn.myanimelist.net/images/manga/2/258749l.jpg",
    type: "manga",
  },
  {
    id: 642,
    name: "Vinland Saga",
    img: "https://cdn.myanimelist.net/images/manga/2/188925l.jpg",
    type: "manga",
  },
  {
    id: 70345,
    name: "Grand Blue",
    img: "https://cdn.myanimelist.net/images/manga/2/166124l.jpg",
    type: "manga",
  },
  {
    id: 25,
    name: "Fullmetal Alchemist",
    img: "https://cdn.myanimelist.net/images/manga/3/243675l.jpg",
    type: "manga",
  },
  {
    id: 4632,
    name: "Oyasumi Punpun",
    img: "https://cdn.myanimelist.net/images/manga/3/266834l.jpg",
    type: "manga",
  },
  {
    id: 16765,
    name: "Kingdom",
    img: "https://cdn.myanimelist.net/images/manga/2/171872l.jpg",
    type: "manga",
  },
  {
    id: 44489,
    name: "Houseki no Kuni",
    img: "https://cdn.myanimelist.net/images/manga/1/115443l.jpg",
    type: "manga",
  },
  {
    id: 3,
    name: "20th Century Boys",
    img: "https://cdn.myanimelist.net/images/manga/5/260006l.jpg",
    type: "manga",
  },
  {
    id: 1303,
    name: "Ashita no Joe",
    img: "https://cdn.myanimelist.net/images/manga/1/268827l.jpg",
    type: "manga",
  },
  {
    id: 657,
    name: "Real",
    img: "https://cdn.myanimelist.net/images/manga/2/115969l.jpg",
    type: "manga",
  },
  {
    id: 14893,
    name: "Monogatari Series: First Season",
    img: "https://cdn.myanimelist.net/images/manga/2/279887l.jpg",
    type: "manga",
  },
  {
    id: 90125,
    name: "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen",
    img: "https://cdn.myanimelist.net/images/manga/3/188896l.jpg",
    type: "manga",
  },
  {
    id: 126479,
    name: "Mikkakan no Koufuku",
    img: "https://cdn.myanimelist.net/images/manga/3/248674l.jpg",
    type: "manga",
  },
  {
    id: 23751,
    name: "Monogatari Series: Second Season",
    img: "https://cdn.myanimelist.net/images/manga/2/181553l.jpg",
    type: "manga",
  },
  {
    id: 104,
    name: "Yotsuba to!",
    img: "https://cdn.myanimelist.net/images/manga/5/259524l.jpg",
    type: "manga",
  },
  {
    id: 1224,
    name: "3-gatsu no Lion",
    img: "https://cdn.myanimelist.net/images/manga/2/52283l.jpg",
    type: "manga",
  },
  {
    id: 336,
    name: "GTO",
    img: "https://cdn.myanimelist.net/images/manga/2/172982l.jpg",
    type: "manga",
  },
  {
    id: 56805,
    name: "Koe no Katachi",
    img: "https://cdn.myanimelist.net/images/manga/1/120529l.jpg",
    type: "manga",
  },
  {
    id: 89357,
    name: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e",
    img: "https://cdn.myanimelist.net/images/manga/2/177958l.jpg",
    type: "manga",
  },
  {
    id: 34053,
    name: "Umineko no Naku Koro ni Chiru - Episode 8: Twilight of the Golden Witch",
    img: "https://cdn.myanimelist.net/images/manga/3/206205l.jpg",
    type: "manga",
  },
];
